[versions]
agp = "8.13.0"
extLatex = "4.6.2"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
markwon = "4.6.2"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
prism4j = "1.1.0"
prism4jBundler = "2.0.0"
prism4jThemeDefault = "1.1.0"
prism4jThemeDefaultVersion = "2.0.0"
prism4jVersion = "2.0.0"
recyclerview = "1.3.2"
lifecycleLivedataKtx = "2.8.6"
lifecycleViewmodelKtx = "2.8.6"
navigationFragment = "2.8.4"
navigationUi = "2.8.4"
annotation = "1.9.1"
kotlin = "2.0.21"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.09.00"

[libraries]
ext-latex = { module = "io.noties.markwon:ext-latex", version.ref = "extLatex" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
markwon = { module = "io.noties:markwon", version.ref = "markwon" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
noties-prism4j-theme-default = { module = "io.noties:prism4j-theme-default", version.ref = "prism4jThemeDefault" }
prism4j = { module = "io.noties:prism4j", version.ref = "prism4j" }
prism4j-bundler = { module = "io.noties:prism4j-bundler", version.ref = "prism4jBundler" }
prism4j-languages = { module = "io.noties:prism4j-languages", version.ref = "prism4jBundler" }
prism4j-theme-default-v200 = { module = "io.noties:prism4j-theme-default", version.ref = "prism4jThemeDefaultVersion" }
prism4j-v200 = { module = "io.noties:prism4j", version.ref = "prism4jVersion" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

